apiVersion: v1
kind: ServiceAccount
metadata:
  name: secretsprovider
---
apiVersion: v1
kind: Service
metadata:
  name: secretsprovider
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    deployment: secretsprovider
  type: LoadBalancer
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: secretsprovider
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: secretsprovider
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secretsprovider
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: secretsprovider
  strategy: {}
  template:
    metadata:
      labels:
        deployment: secretsprovider
      annotations:
        conjur.org/container-mode: sidecar
        conjur.org/secrets-destination: file
        conjur.org/jwt-token-path: /var/run/secrets/tokens/jwt
        conjur.org/conjur-secrets.cityapp-secretsprovider: |
          - dbaddr: db_cityapp/address
          - dbuser: db_cityapp/username
          - dbpass: db_cityapp/password
        conjur.org/secret-file-path.cityapp-secretsprovider: ./worlddb.json
        conjur.org/secret-file-format.cityapp-secretsprovider: json
        conjur.org/secrets-refresh-interval: 10s
    spec:
      serviceAccount: secretsprovider
      containers:
      - name: cityapp
        image: docker.io/joetanx/cityapp:php
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: conjur-secrets
            mountPath: /conjur
            readOnly: true
      - name: secretsprovider
        image: docker.io/cyberark/secrets-provider-for-k8s:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: podinfo
          mountPath: /conjur/podinfo
        - name: conjur-secrets
          mountPath: /conjur/secrets
        - name: jwt-token
          mountPath: /var/run/secrets/tokens
        env:
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        envFrom:
          - configMapRef:
              name: apps-cm
      volumes:
        - name: podinfo
          downwardAPI:
            items:
              - path: annotations
                fieldRef:
                  fieldPath: metadata.annotations
        - name: conjur-secrets
          emptyDir:
            medium: Memory
        - name: jwt-token
          projected:
            sources:
              - serviceAccountToken:
                  path: jwt
                  expirationSeconds: 6000
                  audience: vxlab