apiVersion: v1
kind: Service
metadata:
  name: follower
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    deployment: follower
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: follower
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: follower
  template:
    metadata:
      labels:
        deployment: follower
    spec:
      serviceAccountName: follower
      containers:
      - name: conjur-appliance
        image: image-registry.openshift-image-registry.svc:5000/conjur/conjur-appliance:13.0.0.1
        command: ["/tmp/seedfile/start-follower.sh"]
        securityContext:
          privileged: true
        imagePullPolicy: IfNotPresent
        env:
          - name: SEEDFILE_DIR
            value: /tmp/seedfile
          - name: CONJUR_AUTHENTICATORS
            value: authn-jwt/ocp
        readinessProbe:
          httpGet:
            path: /health
            port: 443
            scheme: HTTPS
          initialDelaySeconds: 15
          timeoutSeconds: 5
        volumeMounts:
          - name: seedfile
            mountPath: /tmp/seedfile
            readOnly: true
      initContainers:
      - name: authenticator
        image: docker.io/cyberark/dap-seedfetcher
        imagePullPolicy: IfNotPresent
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: FOLLOWER_HOSTNAME
            value: follower
          - name: SEEDFILE_DIR
            value: /tmp/seedfile
          - name: JWT_TOKEN_PATH
            value: /var/run/secrets/tokens/jwt
          - name: AUTHENTICATOR
            value: authn-jwt
        envFrom:
          - configMapRef:
              name: follower-cm
        volumeMounts:
          - name: seedfile
            mountPath: /tmp/seedfile
          - name: conjur-token
            mountPath: /run/conjur
          - name: jwt-token
            mountPath: /var/run/secrets/tokens
      volumes:
      - name: seedfile
        emptyDir:
          medium: Memory
      - name: conjur-token
        emptyDir:
          medium: Memory
      - name: jwt-token
        projected:
          sources:
          - serviceAccountToken:
              audience: vxlab
              path: jwt
              expirationSeconds: 6000
# https://access.redhat.com/solutions/3696301
      hostAliases:
      - ip: 192.168.17.90
        hostnames:
        - conjur.vx